In [1]:
# 파라미터를 업데이트 할때 마다 Descent method 에 미분값을 취하기 때문에 미분계산이 필요함

In [2]:
import torch

In [3]:
# default는 False
x = torch.ones(2,2, requires_grad=True)

In [4]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
y = x+1
y

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [6]:
z = 2*y**2
res = z.mean()

In [7]:
#최적화 - 손실함수를 기준으로 해서 각 변수마다 미분을 실행
res

tensor(8., grad_fn=<MeanBackward0>)

In [8]:
# d(res)/dx_i
# res = (z_1 + .. z_4)/4
# z_i = 2y_i ** 2
# z_i = 2(x_i+1)**2
res.backward()

In [11]:
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])


In [ ]:
import torch.nn as nn
import torch.nn.funtional as F