In [1]:
# Torch : the torch package contains data structures for multi-dimensional tensors
#         and mathematical operations over these are defined.

In [ ]:
# 1. 텐서 생성방법
# 2. 텐서 연산방법
# 3. 텐서 사이즈 변환
# 4. 텐서 인덱싱 하는 방법
# 5. 텐서 스칼라 값을 뽑아 내는 방법

In [2]:
import torch
import numpy as np

In [4]:
x = torch.empty(5,4)
x

tensor([[3.0473e-36, 4.5822e-41, 3.0473e-36, 4.5822e-41],
        [7.7234e-38, 4.5822e-41, 1.4442e-38, 0.0000e+00],
        [1.4442e-38, 0.0000e+00, 1.5294e-38, 0.0000e+00],
        [1.5294e-38, 0.0000e+00, 1.5295e-38, 0.0000e+00],
        [1.5295e-38, 0.0000e+00, 1.5295e-38, 0.0000e+00]])

In [5]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.zeros(2)

tensor([0., 0.])

In [7]:
torch.rand(5,6)

tensor([[0.3649, 0.1946, 0.2230, 0.9656, 0.5783, 0.2601],
        [0.3518, 0.2814, 0.7714, 0.3715, 0.7556, 0.9072],
        [0.3872, 0.2418, 0.6350, 0.3503, 0.8072, 0.6375],
        [0.9774, 0.4556, 0.2184, 0.3298, 0.9664, 0.7551],
        [0.3353, 0.6401, 0.6342, 0.1082, 0.2460, 0.5385]])

In [8]:
l = [13,4]
r = np.array([4,56,7])

In [9]:
torch.tensor(l)

tensor([13,  4])

In [10]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [11]:
x.size()

torch.Size([5, 4])

In [12]:
type(x)

torch.Tensor

In [13]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.1262, 0.3923],
        [0.3623, 0.6540]])
tensor([[0.5973, 0.4589],
        [0.6441, 0.1018]])


In [14]:
x+y

tensor([[0.7235, 0.8512],
        [1.0064, 0.7558]])

In [15]:
torch.add(x,y)

tensor([[0.7235, 0.8512],
        [1.0064, 0.7558]])

In [17]:
y.add(x)

tensor([[0.7235, 0.8512],
        [1.0064, 0.7558]])

In [18]:
#inplace 방식 엑스를 더해서 y를 대체함
y.add_(x)

tensor([[0.7235, 0.8512],
        [1.0064, 0.7558]])

In [19]:
y

tensor([[0.7235, 0.8512],
        [1.0064, 0.7558]])

In [21]:
y[:,1]

tensor([0.8512, 0.7558])

In [23]:
x = torch.rand(8,8)
x

tensor([[0.0423, 0.1629, 0.1513, 0.7144, 0.6563, 0.1670, 0.0828, 0.1118],
        [0.9080, 0.5624, 0.8584, 0.5756, 0.6822, 0.1305, 0.2561, 0.0229],
        [0.3677, 0.7952, 0.0364, 0.2751, 0.8419, 0.3854, 0.8984, 0.3149],
        [0.5566, 0.3171, 0.4026, 0.2615, 0.5146, 0.8528, 0.0707, 0.1707],
        [0.1418, 0.8290, 0.3606, 0.9291, 0.8933, 0.2420, 0.5338, 0.8811],
        [0.6783, 0.2770, 0.9642, 0.2494, 0.2535, 0.0651, 0.9376, 0.9118],
        [0.5509, 0.7134, 0.7920, 0.0281, 0.6873, 0.6953, 0.5898, 0.7996],
        [0.5308, 0.3497, 0.7283, 0.5023, 0.2146, 0.5470, 0.1931, 0.5231]])

In [25]:
#1열로 변환
# 사이즈 변환 -> CNN 컨볼류션 레이어 연산에서 풀리 커넥티드 레이어로 정사각형 레이어를 1열로 펴줄때 사용
x.view(64)

tensor([0.0423, 0.1629, 0.1513, 0.7144, 0.6563, 0.1670, 0.0828, 0.1118, 0.9080,
        0.5624, 0.8584, 0.5756, 0.6822, 0.1305, 0.2561, 0.0229, 0.3677, 0.7952,
        0.0364, 0.2751, 0.8419, 0.3854, 0.8984, 0.3149, 0.5566, 0.3171, 0.4026,
        0.2615, 0.5146, 0.8528, 0.0707, 0.1707, 0.1418, 0.8290, 0.3606, 0.9291,
        0.8933, 0.2420, 0.5338, 0.8811, 0.6783, 0.2770, 0.9642, 0.2494, 0.2535,
        0.0651, 0.9376, 0.9118, 0.5509, 0.7134, 0.7920, 0.0281, 0.6873, 0.6953,
        0.5898, 0.7996, 0.5308, 0.3497, 0.7283, 0.5023, 0.2146, 0.5470, 0.1931,
        0.5231])

In [27]:
# -1자주 사용되는 표현 나머지 것들이 고정되는 값이어야 함 16이 나누어지는지가 확인되어야 함
x.view(-1,16)

tensor([[0.0423, 0.1629, 0.1513, 0.7144, 0.6563, 0.1670, 0.0828, 0.1118, 0.9080,
         0.5624, 0.8584, 0.5756, 0.6822, 0.1305, 0.2561, 0.0229],
        [0.3677, 0.7952, 0.0364, 0.2751, 0.8419, 0.3854, 0.8984, 0.3149, 0.5566,
         0.3171, 0.4026, 0.2615, 0.5146, 0.8528, 0.0707, 0.1707],
        [0.1418, 0.8290, 0.3606, 0.9291, 0.8933, 0.2420, 0.5338, 0.8811, 0.6783,
         0.2770, 0.9642, 0.2494, 0.2535, 0.0651, 0.9376, 0.9118],
        [0.5509, 0.7134, 0.7920, 0.0281, 0.6873, 0.6953, 0.5898, 0.7996, 0.5308,
         0.3497, 0.7283, 0.5023, 0.2146, 0.5470, 0.1931, 0.5231]])

In [29]:
#tensor 에서 넘파이로 넘어가는 것
# type(y)
y = x.numpy()
type(y)

numpy.ndarray

In [31]:
x = torch.ones(1)

In [32]:
#tensor 안에 값을 추출하려면은 item
x.item()

1.0